/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import io from "@strapi-community/plugin-io/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    io: io,
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
  },
});
